export const MOTIVATIONAL_QUOTES = [
  "Specialization is for insects.",
  "Study the science of art. Study the art of science.",
  "Develop your senses- learn how to see. Realize that everything connects to everything else.",
  "The noblest pleasure is the joy of understanding.",
  "Simplicity is the ultimate sophistication.",
  "A Jack of all trades is a master of integration.",
  "To know and not to do is not yet to know.",
  "You cannot dig a hole in a different place by digging the same hole deeper.",
  "Knowledge without application is theft.",
  "The creative adult is the child who survived.",
  "Whatever you can do, or dream you can, begin it.",
  "Your work is to discover your work and then with all your heart to give yourself to it.",
  "I am always doing that which I cannot do, in order that I may learn how to do it.",
  "He who has a why to live can bear almost any how.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "The impediment to action advances action. What stands in the way becomes the way.",
  "Waste no more time arguing about what a good man should be. Be one.",
  "It is not death that a man should fear, but he should fear never beginning to live.",
  "If you want to improve, be content to be thought foolish and stupid.",
  "Luck is what happens when preparation meets opportunity.",
  "It is impossible for a man to learn what he thinks he already knows.",
  "No man is free who is not master of himself.",
  "Whatever you are, be a good one.",
  "The only true wisdom is in knowing you know nothing.",
  "Education is the kindling of a flame, not the filling of a vessel.",
  "The mind is not a vessel to be filled, but a fire to be kindled.",
  "First principles, Clarice. Simplicity. Read Marcus Aurelius. Of each particular thing ask: what is it in itself?",
  "I think, therefore I am.",
  "Wisdom begins in wonder.",
  "The unexamined life is not worth living.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "Only those who will risk going too far can possibly find out how far one can go.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "Be the change that you wish to see in the world.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "If you tell the truth, you don't have to remember anything.",
  "A friend to all is a friend to none.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.",
  "We accept the love we think we deserve.",
  "It is never too late to be what you might have been.",
  "Everything you can imagine is real.",
  "Life isn't about finding yourself. Life is about creating yourself.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "You miss 100% of the shots you don't take.",
  "The journey of a thousand miles begins with one step.",
  "That which does not kill us makes us stronger.",
  "Life is what happens when you're busy making other plans.",
  "Get busy living or get busy dying.",
  "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  "Believe you can and you're halfway there.",
  "The only impossible journey is the one you never begin.",
  "Change your thoughts and you change your world.",
  "It always seems impossible until it's done.",
  "Do not wait; the time will never be 'just right'.",
  "Your time is limited, so don't waste it living someone else's life.",
  "The best way to predict the future is to create it.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The ones who are crazy enough to think they can change the world, are the ones who do.",
  "Do one thing every day that scares you.",
  "What is the point of being alive if you don't at least try to do something remarkable?",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Stop chasing the money and start chasing the passion.",
  "All progress takes place outside the comfort zone.",
  "The way to get started is to quit talking and begin doing.",
  "Don't let the fear of losing be greater than the excitement of winning.",
  "If you really look closely, most overnight successes took a long time.",
  "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction.",
  "Go as far as you can see; when you get there, you'll be able to see further.",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Creativity is intelligence having fun.",
  "Do what you can, with what you have, where you are.",
  "It's not whether you get knocked down, it's whether you get up.",
  "Security is mostly a superstition. Life is either a daring adventure or nothing.",
  "The man who has confidence in himself gains the confidence of others.",
  "The future belongs to the competent. Get good, get better, be the best!",
  "A room without books is like a body without a soul.",
  "So many books, so little time.",
  "Think before you speak. Read before you think.",
  "Whatever the mind of man can conceive and believe, it can achieve.",
  "Strive not to be a success, but rather to be of value.",
  "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.",
  "I attribute my success to this: I never gave or took any excuse.",
  "You become what you believe.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Definiteness of purpose is the starting point of all achievement.",
  "We become what we think about.",
  "Life is 10% what happens to me and 90% how I react to it.",
  "If you do what you've always done, you'll get what you've always gotten.",
  "Dream big and dare to fail.",
  "You may be disappointed if you fail, but you are doomed if you don't try.",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "Action is the foundational key to all success.",
  "Everything has beauty, but not everyone can see.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "When I let go of what I am, I become what I might be.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "Happiness is not something readymade. It comes from your own actions.",
  "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.",
  "You can't use up creativity. The more you use, the more you have.",
  "The best revenge is massive success.",
  "I am thankful for all of those who said NO to me. It's because of them I'm doing it myself.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "Certain things catch your eye, but pursue only those that capture the heart.",
  "Believe you can and you're halfway there.",
  "Change your thoughts and you change your world.",
  "Start where you are. Use what you have. Do what you can.",
  "Fall seven times and stand up eight.",
  "Everything you've ever wanted is on the other side of fear.",
  "We need much less than we think we need.",
  "Make it simple, but significant.",
  "Simplicity is the essence of happiness.",
  "Silence is a source of great strength.",
  "Adopt the pace of nature: her secret is patience.",
  "Real knowledge is to know the extent of one's ignorance.",
  "He who knows, does not speak. He who speaks, does not know.",
  "A journey of a thousand miles begins with a single step.",
  "When you are content to be simply yourself and don't compare or compete, everybody will respect you.",
  "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.",
  "Simplicity is the soul of efficiency.",
  "Life is really simple, but we insist on making it complicated.",
  "The art of being wise is the art of knowing what to overlook.",
  "Knowledge is learning something every day. Wisdom is letting go of something every day.",
  "Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you.",
  "Act without expectation.",
  "Nature does not hurry, yet everything is accomplished.",
  "To the mind that is still, the whole universe surrenders.",
  "The usefulness of a pot comes from its emptiness.",
  "When I let go of what I am, I become what I might be.",
  "Mastering others is strength. Mastering yourself is true power.",
  "Great acts are made up of small deeds.",
  "The flame that burns Twice as bright burns half as long.",
  "He who is contented is rich.",
  "If you realize that all things change, there is nothing you will try to hold on to.",
  "Anticipate the difficult by managing the easy.",
  "The wise man is one who, knows, what he does not know.",
  "Manifest plainness, embrace simplicity, reduce selfishness, have few desires.",
  "Respond to every call that excites your spirit.",
  "Your vision will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes.",
  "Knowing your own darkness is the best method for dealing with the darknesses of other people.",
  "Until you make the unconscious conscious, it will direct your life and you will call it fate.",
  "The privilege of a lifetime is to become who you truly are.",
  "I am not what happened to me, I am what I choose to become.",
  "You represent the universe knowing itself.",
  "Every addiction starts with pain and ends with pain.",
  "Where your fear is, there is your task.",
  "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.",
  "Thinking is difficult, that’s why most people judge.",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
  "Don't grieve. Anything you lose comes round in another form.",
  "You were born with wings, why prefer to crawl through life?",
  "Raise your words, not voice. It is rain that grows flowers, not thunder.",
  "Ignore those that make you fearful and sad, that degrade you back towards disease and death.",
  "Set your life on fire. Seek those who fan your flames.",
  "I know you're tired but come, this is the way.",
  "The wound is the place where the Light enters you.",
  "Stop acting so small. You are the universe in ecstatic motion.",
  "What you seek is seeking you.",
  "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.",
  "It is the quality of our work which will please God and not the quantity.",
  "Patience is not sitting and waiting, it is foreseeing. It is looking at the thorn and seeing the rose, looking at the night and seeing the day.",
  "Words are a pretext. It is the inner bond that draws one person to another, not words.",
  "Silence is the language of God, all else is poor translation.",
  "Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.",
  "The lion is most handsome when looking for food.",
  "Sell your cleverness and buy bewilderment.",
  "There is a voice that doesn’t use words. Listen.",
  "Everything in the universe is within you. Ask all from yourself.",
  "Lovers don't finally meet somewhere. They're in each other all along.",
  "Run from what's comfortable. Forget safety. Live where you fear to live. Destroy your reputation. Be notorious.",
  "Wear gratitude like a cloak, and it will feed every corner of your life.",
  "Close your eyes. Fall in love. Stay there.",
  "Only from the heart can you touch the sky.",
  "Let the beauty of what you love be what you do.",
  "Keep knocking, and the joy inside will eventually open a window and look out to see who's there."
];

export const GOODNIGHT_QUOTES = [
  "Rest is the workshop of the mind.",
  "The stars await your dreams.",
  "Sleep is the golden chain that ties health and our bodies together.",
  "Let the silence heal you.",
  "Tomorrow is a new canvas.",
  "Disconnect to reconnect.",
  "Peace comes from within. Do not seek it without.",
  "Rest not to quit, but to recover.",
  "Nature's soft nurse awaits.",
  "The universe speaks in silence.",
  "Sleep is the best meditation.",
  "Man should forget his anger before he lies down to sleep.",
  "A well-spent day brings happy sleep.",
  "Take rest; a field that has rested gives a bountiful crop.",
  "There is virtue in work and there is virtue in rest. Use both and overlook neither.",
  "The minute anyone's getting too anxious I say, 'You must eat and you must sleep.' They're the two vital elements for a healthy life.",
  "Each night, when I go to sleep, I die. And the next morning, when I wake up, I am reborn.",
  "Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day.",
  "Never go to sleep without a request to your subconscious.",
  "Sleep is the interest we have to pay on the capital which is called in at death; and the higher the rate of interest and the more regularly it is paid, the further the date of redemption is postponed.",
  "Even a soul submerged in sleep is hard at work and helps make something of the world.",
  "Your future depends on your dreams, so go to sleep.",
  "Sleep that knits up the raveled sleave of care.",
  "The woods are lovely, dark and deep. But I have promises to keep, and miles to go before I sleep.",
  "Throw off your worries when you throw off your clothes at night.",
  "No day is so bad it can't be fixed with a nap.",
  "Fatigue is the best pillow.",
  "Happiness consists of getting enough sleep. Just that, nothing more.",
  "A ruffled mind makes a restless pillow.",
  "Anything important is worth doing slowly.",
  "Slow down and everything you are chasing will come around and catch you.",
  "In an age of speed, I began to think, nothing could be more invigorating than going slow.",
  "There is more to life than increasing its speed.",
  "Be slow to speak, and only after having first listened quietly, so that you may understand the meaning, leanings, and wishes of those who do speak. Thus you will better know when to speak and when to be silent.",
  "Slow down and enjoy life. It's not only the scenery you miss by going too fast - you also miss the sense of where you are going and why.",
  "The trees that are slow to grow bear the best fruit.",
  "Adopt the pace of nature: her secret is patience.",
  "For fast-acting relief, try slowing down.",
  "Smile, breathe and go slowly.",
  "He that can take rest is greater than he that can take cities.",
  "Rest and be thankful.",
  "Every now and then go away, have a little relaxation, for when you come back to your work your judgment will be surer.",
  "Sometimes the most urgent thing you can possibly do is take a complete rest.",
  "If you get tired, learn to rest, not to quit.",
  "Resting is not laziness, it's medicine.",
  "Quiet the mind, and the soul will speak.",
  "Within you, there is a stillness and a sanctuary to which you can retreat at any time and be yourself.",
  "Silence is a true friend who never betrays.",
  "The more you know, the less you need to say.",
  "In the silence of the heart, God speaks.",
  "Listen to the silence. It has so much to say.",
  "True silence is the rest of the mind, and is to the spirit what sleep is to the body, nourishment and refreshment.",
  "Everything that's created comes out of silence.",
  "Silence is the sleep that nourishes wisdom.",
  "I have often regretted my speech, never my silence.",
  "Work hard in silence, let your success be your noise.",
  "Silence at the proper season is wisdom, and better than any speech.",
  "The night is the hardest time to be alive and 4am knows all my secrets.",
  "I love the silent hour of night, For blissful dreams may then arise.",
  "Night is a world lit by itself.",
  "The darker the night, the brighter the stars.",
  "I have loved the stars too fondly to be fearful of the night.",
  "Night time is really the best time to work. All the ideas are there to be yours because everyone else is asleep.",
  "The night walks down the sky with the moon in her hand.",
  "It was a rich and gorgeous sunset - an American sunset; and the ruddy glow of the sky was reflected from some extensive pools of water among the shadowy copses in the meadow below.",
  "Let the night take you. Let the stars evaporate into your dreams. Let sleep be the only comfort for you to believe.",
  "The moon will guide you through the night with her brightness, but she will always dwell in the darkness, in order to be seen.",
  "Night, the beloved. Night, when words fade and things come alive.",
  "Those who dream by day are cognizant of many things which escape those who dream only by night.",
  "Dreams are the touchstones of our characters.",
  "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "All our dreams can come true, if we have the courage to pursue them.",
  "Dream no small dreams for they have no power to move the hearts of men.",
  "You see things; and you say 'Why?' But I dream things that never were; and I say 'Why not?'",
  "A dream you dream alone is only a dream. A dream you dream together is reality.",
  "Deep into that darkness peering, long I stood there, wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.",
  "Dreams are illustrations... from the book your soul is writing about you.",
  "Go confidently in the direction of your dreams! Live the life you've imagined.",
  "Hope is a waking dream.",
  "Without leaps of imagination, or dreaming, we lose the excitement of possibilities. Dreaming, after all, is a form of planning.",
  "Dreams are today's answers to tomorrow's questions.",
  "The only thing that will stop you from fulfilling your dreams is you.",
  "If you can dream it, you can do it.",
  "Don't let someone else's opinion of you become your reality.",
  "Look at the stars. See their beauty. And in that beauty, see yourself.",
  "The sky is the daily bread of the eyes.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "In every walk with nature one receives far more than he seeks.",
  "Nature is not a place to visit. It is home.",
  "Look deep into nature, and then you will understand everything better.",
  "The earth has music for those who listen.",
  "To sit in the shade on a fine day and look upon verdure is the most perfect refreshment.",
  "Colors are the smiles of nature.",
  "Nature always wears the colors of the spirit.",
  "If you truly love nature, you will find beauty everywhere.",
  "The best thing one can do when it's raining is to let it rain.",
  "Nature does not hurry, yet everything is accomplished.",
  "The clearest way into the Universe is through a forest wilderness.",
  "Just living is not enough... one must have sunshine, freedom, and a little flower.",
  "I go to nature to be soothed and healed, and to have my senses put in order.",
  "Study nature, love nature, stay close to nature. It will never fail you.",
  "There is a pleasure in the pathless woods.",
  "The poetry of earth is never dead.",
  "Wilderness is not a luxury but a necessity of the human spirit.",
  "Time spent amongst trees is never wasted time.",
  "Sunset is still my favorite color, and rainbow is second.",
  "Every sunset brings the promise of a new dawn.",
  "Light tomorrow with today.",
  "This is the beginning of a new day. You have been given this day to use as you will. You can waste it or use it for good. What you do today is important because you are exchanging a day of your life for it. When tomorrow comes, this day will be gone forever; in its place is something that you have left behind... let it be something good.",
  "With the new day comes new strength and new thoughts.",
  "Every morning we are born again. What we do today is what matters most.",
  "Morning is an important time of day, because how you spend your morning can often tell you what kind of day you are going to have.",
  "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love.",
  "Today's accomplishments were yesterday's impossibilities.",
  "Don't count the days, make the days count.",
  "The sun is a daily reminder that we too can rise again from the darkness, that we too can shine our own light.",
  "New month, new intentions, new goals, new love, new light, and new beginnings.",
  "Opportunities are like sunrises. If you wait too long, you miss them.",
  "Your attitude is like a box of crayons that color your world. Constantly color your picture gray, and your picture will always be gray. Try adding some bright colors to the picture by including humor, and your picture begins to lighten up.",
  "Keep looking up! I learn from the past, dream about the future and look up. There's nothing like a beautiful sunset to end a healthy day.",
  "May your choices reflect your hopes, not your fears.",
  "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.",
  "Calmness is the cradle of power.",
  "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.",
  "Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.",
  "Worry does not empty tomorrow of its sorrow, it empties today of its strength.",
  "Tension is who you think you should be. Relaxation is who you are.",
  "Doing nothing is better than being busy doing nothing.",
  "Sometimes the most productive thing you can do is relax.",
  "Your calm mind is the ultimate weapon against your challenges.",
  "Breath is the bridge which connects life to consciousness, which unites your body to your thoughts.",
  "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.",
  "Nothing can bring you peace but yourself.",
  "If you want to conquer the anxiety of life, live in the moment, live in the breath.",
  "You cannot find peace by avoiding life.",
  "Peace involves a profound confidence that you are where you are meant to be.",
  "Let go of thoughts that don't make you strong.",
  "A happy life consists in tranquility of mind.",
  "The more tranquil a man becomes, the greater is his success, his influence, his power for good.",
  "Tranquility is the old man's milk.",
  "One of the best lessons you can learn in life is to master how to remain calm.",
  "When you find peace within yourself, you become the kind of person who can live at peace with others.",
  "Serenity is not freedom from the storm, but peace amid the storm.",
  "Peace is a day-to-day problem, the product of a multitude of events and judgments. Peace is not an 'is', it is a 'becoming'.",
  "World peace begins with inner peace.",
  "Inner peace is the new success.",
  "Do not let the behavior of others destroy your inner peace.",
  "Nobody can bring you peace but yourself.",
  "The life of inner peace, being harmonious and without stress, is the easiest type of existence.",
  "Peace is liberty in tranquility.",
  "When we are unable to find tranquility within ourselves, it is useless to seek it elsewhere.",
  "For every minute you remain angry, you give up sixty seconds of peace of mind."
];